[package]
authors = ["Rouven Reuter"]
description = "A Linter implementation for Phenopackets"
edition = "2024"
homepage = "https://robinsongroup.github.io/"
license = "MIT"
name = "phenolint"
version = "0.1.0"

[dependencies]
phenopackets = { version = "0.2.2-post1", features = ["serde"] }
serde = "1.0.228"
serde_json = "1.0.145"
ontolius = "0.6.0"
regex = "1.12.2"
log = "0.4.28"


[dev-dependencies]
rstest = "0.26.1"
pretty_assertions = "1.4.1"
once_cell = "1.21.3"