[package]
name = "phenolint-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
regex = "1.12.2"
once_cell = "1.21.3"
convert_case = "0.9.0"
proc-macro2 = "1.0.103"
